export const employees = [
  {
    id: 1,
    name: 'Ruby Goadby',
    gender: 'Male',
    age: 24,
    job_title: 'Teacher',
    department: 'Sales',
    performance_rating: 5,
    attendance_percentage: 87.87,
    overtime_hours: 7.55,
    team_size: 11,
    communication_skills: 'good',
    employee_status: 'on leave',
  },
  {
    id: 2,
    name: 'Terencio Feeney',
    gender: 'Male',
    age: 24,
    job_title: 'Social Worker',
    department: 'Legal',
    performance_rating: 4,
    attendance_percentage: 87.2,
    overtime_hours: 19.8,
    team_size: 3,
    communication_skills: 'average',
    employee_status: 'active',
  },
  {
    id: 3,
    name: 'Orazio Libbis',
    gender: 'Male',
    age: 23,
    job_title: 'Nurse Practicioner',
    department: 'Services',
    performance_rating: 3,
    attendance_percentage: 96.54,
    overtime_hours: 15.61,
    team_size: 9,
    communication_skills: 'good',
    employee_status: 'active',
  },
  {
    id: 4,
    name: 'Meara Jewell',
    gender: 'Female',
    age: 26,
    job_title: 'Analyst Programmer',
    department: 'Research and Development',
    performance_rating: 8,
    attendance_percentage: 36.57,
    overtime_hours: 5.66,
    team_size: 7,
    communication_skills: 'good',
    employee_status: 'active',
  },
  {
    id: 5,
    name: 'Farlee Solomonides',
    gender: 'Male',
    age: 23,
    job_title: 'Human Resources Assistant IV',
    department: 'Business Development',
    performance_rating: 7,
    attendance_percentage: 57.37,
    overtime_hours: 17.96,
    team_size: 9,
    communication_skills: 'poor',
    employee_status: 'active',
  },
  {
    id: 6,
    name: 'Brandice Kilbee',
    gender: 'Female',
    age: 21,
    job_title: 'VP Sales',
    department: 'Product Management',
    performance_rating: 2,
    attendance_percentage: 31.24,
    overtime_hours: 15.78,
    team_size: 6,
    communication_skills: 'good',
    employee_status: 'active',
  },
  {
    id: 7,
    name: 'Helsa Grealy',
    gender: 'Agender',
    age: 39,
    job_title: 'Recruiting Manager',
    department: 'Training',
    performance_rating: 9,
    attendance_percentage: 73.98,
    overtime_hours: 13.99,
    team_size: 15,
    communication_skills: 'excellent',
    employee_status: 'active',
  },
  {
    id: 8,
    name: 'Kimmie Bowart',
    gender: 'Female',
    age: 23,
    job_title: 'Assistant Professor',
    department: 'Services',
    performance_rating: 10,
    attendance_percentage: 41.31,
    overtime_hours: 19.8,
    team_size: 3,
    communication_skills: 'average',
    employee_status: 'active',
  },
  {
    id: 9,
    name: 'Desmond Bligh',
    gender: 'Male',
    age: 31,
    job_title: 'Software Test Engineer II',
    department: 'Services',
    performance_rating: 4,
    attendance_percentage: 4.27,
    overtime_hours: 4.57,
    team_size: 9,
    communication_skills: 'poor',
    employee_status: 'on leave',
  },
  {
    id: 10,
    name: 'Dana Schuelcke',
    gender: 'Male',
    age: 37,
    job_title: 'Safety Technician II',
    department: 'Training',
    performance_rating: 5,
    attendance_percentage: 42.8,
    overtime_hours: 19.09,
    team_size: 17,
    communication_skills: 'average',
    employee_status: 'on leave',
  },
]
